// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsprpz2WoZCPBh5vmeJmPb_oXHNMMHaBE',
    appId: '1:486591331456:web:506b4bb09a44394ca5fa65',
    messagingSenderId: '486591331456',
    projectId: 'uxzero-base',
    authDomain: 'uxzero-base.firebaseapp.com',
    storageBucket: 'uxzero-base.appspot.com',
    measurementId: 'G-109VX3Z7SM',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsprpz2WoZCPBh5vmeJmPb_oXHNMMHaBE',
    appId: '1:486591331456:web:e18b4631e7f60476a5fa65',
    messagingSenderId: '486591331456',
    projectId: 'uxzero-base',
    authDomain: 'uxzero-base.firebaseapp.com',
    storageBucket: 'uxzero-base.appspot.com',
    measurementId: 'G-N5JKBWBPYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyY6JQrfY6-ahgopYPvlcUuDt-MkQZXGM',
    appId: '1:486591331456:android:7efc9ad72a6d7e73a5fa65',
    messagingSenderId: '486591331456',
    projectId: 'uxzero-base',
    storageBucket: 'uxzero-base.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAaqoQD0NxOQYYdG9plRtVeUG_gSoU_7E',
    appId: '1:486591331456:ios:c9f67a44c691fd04a5fa65',
    messagingSenderId: '486591331456',
    projectId: 'uxzero-base',
    storageBucket: 'uxzero-base.appspot.com',
    iosBundleId: 'com.example.uxzero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAaqoQD0NxOQYYdG9plRtVeUG_gSoU_7E',
    appId: '1:486591331456:ios:c9f67a44c691fd04a5fa65',
    messagingSenderId: '486591331456',
    projectId: 'uxzero-base',
    storageBucket: 'uxzero-base.appspot.com',
    iosBundleId: 'com.example.uxzero',
  );
}
